name: "📋 [要件定義] 工程タスク"
description: "要件定義フェーズ用テンプレート"
title: "[多言語対応] 要件定義"
labels: ["task", "requirements"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ 設定忘れずに
        - **Milestone**: 該当するマイルストーンを設定
        - **親Issue**: 親プロジェクトIssueにリンク

  - type: markdown
    attributes:
      value: |
        ## 📌 工程: 1. 要件定義

  - type: input
    id: duration
    attributes:
      label: "⏱️ 想定期間"
      value: "2日"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "📝 タスク概要"
      value: |
        多言語対応（日英）の要件を明確化し、要件定義書を作成する。
        
        ### 実施内容
        1. 対応言語の確定（日本語・英語）
        2. 多言語化対象の洗い出し
           - UIテキスト（ボタン、ラベル、メッセージ）
           - 商品情報（名前、説明、カテゴリ）
           - エラーメッセージ
           - 通知テンプレート
        3. 対応外スコープの明確化
        4. 言語切り替え方式の検討
        5. ステークホルダーとの合意

  - type: textarea
    id: deliverables
    attributes:
      label: "📦 成果物"
      value: |
        - [ ] 多言語対応要件定義書（`docs/i18n/requirement.md`）
        - [ ] 多言語化対象一覧（UIテキスト、商品情報等）
        - [ ] 用語集（翻訳時の表記統一用）

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ 完了条件"
      value: |
        - [ ] 要件定義書が作成されている
        - [ ] 対応言語・対象範囲が明確化されている
        - [ ] ステークホルダーの承認を得ている

  - type: textarea
    id: dependencies
    attributes:
      label: "🔗 依存関係"
      value: |
        **先行タスク**: なし
        **後続タスク**: 基本設計
