name: "📋 [受け入れテスト] 工程タスク"
description: "受け入れテストフェーズ用テンプレート"
title: "[多言語対応] 受け入れテスト"
labels: ["task", "testing"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ 設定忘れずに
        - **Milestone**: 該当するマイルストーンを設定
        - **親Issue**: 親プロジェクトIssueにリンク

  - type: markdown
    attributes:
      value: |
        ## 📌 工程: 8. 受け入れテスト

  - type: input
    id: duration
    attributes:
      label: "⏱️ 想定期間"
      value: "2日"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "📝 タスク概要"
      value: |
        ステークホルダーによる受け入れテストを実施し、リリース可否を判断する。
        
        ### 実施内容
        1. ステークホルダーデモ
           - 多言語機能のデモンストレーション
           - 質疑応答
        2. ユーザー視点での操作確認
           - 言語切り替えの使いやすさ
           - 翻訳品質の確認
        3. 翻訳内容のレビュー
           - ネイティブチェック（可能であれば）
           - 用語の一貫性確認
        4. 最終承認
           - リリース可否判定
           - 残課題の確認

  - type: textarea
    id: deliverables
    attributes:
      label: "📦 成果物"
      value: |
        - [ ] 受け入れテスト実施記録
        - [ ] ステークホルダーフィードバック一覧
        - [ ] 翻訳レビュー結果
        - [ ] リリース承認書

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ 完了条件"
      value: |
        - [ ] ステークホルダーのデモが完了
        - [ ] 翻訳品質が承認されている
        - [ ] 致命的な問題がない
        - [ ] リリース承認が得られている

  - type: textarea
    id: dependencies
    attributes:
      label: "🔗 依存関係"
      value: |
        **先行タスク**: #システムテスト
        **後続タスク**: リリース
