name: "📁 プロジェクト（親Issue）"
description: "工程管理用の親Issueテンプレート"
title: "[プロジェクト] ECサイトの多言語対応（日英）"
labels: ["project", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ 設定忘れずに
        
        **このIssue作成後、以下を設定してください：**
        - **Milestone**: `Milestone1` を設定
        - **Projects**: GitHub Projects に追加
        
        ---

  - type: markdown
    attributes:
      value: |
        ## 📋 プロジェクト概要
        
        ECサイト（PC Parts Shop）の多言語対応（日本語・英語）を実施します。

  - type: textarea
    id: project-scope
    attributes:
      label: "🎯 プロジェクトスコープ"
      value: |
        ### 目的
        ECサイトを日本語・英語の2言語に対応させ、海外ユーザーの利用を可能にする
        
        ### 対応言語
        - 日本語（ja）- デフォルト
        - 英語（en）
        
        ### 対応範囲
        - UIテキスト（ボタン、ラベル、メッセージ等）
        - 商品情報（商品名、説明、カテゴリ名）
        - エラーメッセージ
        - メール通知テンプレート（将来対応）
        
        ### 対応外
        - ユーザー入力データ（住所、名前等）
        - 過去の注文履歴データ

  - type: textarea
    id: sub-issues
    attributes:
      label: "📝 工程タスク（Sub-Issues）"
      value: |
        以下のSub-Issueを作成し、このIssueにリンクしてください。
        各Sub-Issueは「工程タスク」テンプレートを使用して作成できます。
        
        ### タスクリスト
        
        ```[tasklist]
        ### 工程管理
        - [ ] 要件定義
        - [ ] 基本設計
        - [ ] 詳細設計
        - [ ] 実装・レビュー
        - [ ] 単体テスト
        - [ ] 結合テスト
        - [ ] システムテスト
        - [ ] 受け入れテスト
        - [ ] リリース
        ```
        
        ### 工程詳細
        
        | # | 工程 | 概要 | 想定期間 |
        |---|------|------|---------|
        | 1 | 要件定義 | 多言語対応の要件を明確化 |  |
        | 2 | 基本設計 | i18nアーキテクチャ設計 |  |
        | 3 | 詳細設計 | 翻訳ファイル構造、コンポーネント設計 |  |
        | 4 | 実装・レビュー | コード実装とコードレビュー |  |
        | 5 | 単体テスト | コンポーネント単位のテスト |  |
        | 6 | 結合テスト | 機能間連携テスト |  |
        | 7 | システムテスト | 全体動作確認 |  |
        | 8 | 受け入れテスト | ステークホルダー確認 |  |
        | 9 | リリース | 本番デプロイ |  |

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "✅ 完了条件"
      value: |
        - [ ] 日本語・英語の切り替えが可能
        - [ ] すべてのUIテキストが翻訳済み
        - [ ] 言語設定がブラウザ/ユーザー設定で保持される
        - [ ] 全工程のSub-Issueがクローズ済み
        - [ ] 本番環境にデプロイ完了

  - type: textarea
    id: notes
    attributes:
      label: "📝 備考"
      value: |
        - 関連設計書: `docs/` フォルダ参照
        - 使用ライブラリ: react-i18next（予定）
